### ISSUE TITLE
Error when using the Addon

### ISSUE THREAD

**Issue by esogamer** [jonpacker/HumlefnuggUnitFrames#1]
user:/AddOns/HumlefnuggUnitFrames/events/hf_delegate.lua:9: table index is nil
stack traceback:
    user:/AddOns/HumlefnuggUnitFrames/events/hf_delegate.lua:9: in function 'HFEventDelegate:add'
    user:/AddOns/HumlefnuggUnitFrames/events/hf_unit.lua:4: in function '(main chunk)'

**Comment by esogamer** [comment]
Please fix this!

**Comment by jonpacker** [comment]
I haven't played ESO for a long time and I'm no longer maintaining this module, sorry.

**Comment by esogamer** [comment]
Could you help me fixing it? I have very little scripting knowledge but I love your addon and the design.

**Comment by jonpacker** [comment]
It's likely that the ESO addon APIs changed since I wrote it, and unfortunately I don't have time to learn the new APIs to figure out what the problem is. Sorry. You might be able to get some help from a more active ESO addon forum somewhere.

**Comment by esogamer** [comment]
Okay thank you for the addon so far :+1:
